### ISSUE TITLE
Feature：提高对hexo的toc功能的兼容性

### ISSUE THREAD

**Issue by dyphire** [netbeifeng/hexo-tag-bangumi#2]
感谢大佬开发的这个bangumi插件，效果很漂亮，不过使用中有点小问题。

插件使用中发现它生成的h1和h4标签信息会破坏hexo的toc功能，会被一并解析并破坏markdown文章原有的标题层级信息

问题表现：
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/10/20220110125033.png)

是否有办法优化不以标题信息显示？

**Comment by netbeifeng** [comment]
已更改为 `<span>` 标签，请通过 `npm install hexo-tag-bangumi@0.1.4` 拉取最新版本，之后再重新渲染试试，如果仍然有问题的话，我再看看。

**Comment by dyphire** [comment]
> 已更改为 `<span>` 标签，请通过 `npm install hexo-tag-bangumi@0.1.4` 拉取最新版本，之后再重新渲染试试，如果仍然有问题的话，我再看看。

大佬太给力了。插件更新后重新渲染不会显示标题了，赞。

css副标题的排版似乎出了点问题
官方名越界了
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/01/10/20220110231147.png)

**Comment by dyphire** [comment]
顺便一提，配置文件中的配置项`bangumi`建议重命名下，会和另一个hexo-bilibili-bangumi插件的配置项名称重复，改成~realbangumi~ bangumis？

**Comment by netbeifeng** [comment]
哈哈，感谢你的反馈，大佬可不敢当啊。
问题应该修复了，现在应该不会在同一行了。

另外也非常感谢你反馈的重名问题。
现在在 `_config.yml`  中的配置变量名已替换为： `bangumis`

**Comment by dyphire** [comment]
十分感谢，最新版显示效果一切正常
